### ISSUE TITLE
how to capture the type of subtitles

### ISSUE THREAD

**Issue by windowsales** [bernardro/actor-youtube-scraper#29]
Hi guys. Thanks for this great tool.  We would like a new feature added so that the actor can determine the type of subtitles provided - whether they are user generated, or auto-generated.

This info is available on the youtube video if the actor could click the three dots to reveal the transcripts popup.

See image here: https://ibb.co/dLYcJFv

Can you guys code this for us in the script? We can pay for your work.
Thankyou!

**Comment by zpelechova** [comment]
Hey, sorry for the late reply, let me get back to you asap.

**Comment by zpelechova** [comment]
Hi, sorry again, we are swamped - can you post your project here: https://apify.com/marketplace - it should go really fast there. Zuzka

**Comment by metalwarrior665** [comment]
This feature is now live
