### ISSUE TITLE
How to go to the next page?

### ISSUE THREAD

**Issue by windowsales** [bernardro/actor-youtube-scraper#31]
Hi there, I managed to get the actor working and returning 50 results.  In the channel we are getting however, there are much more than 50 results. How can we get the actor to step through ALL pages so that it can scrape all videos of the channel, not just the first 50?

**Comment by zpelechova** [comment]
Hey, just change the number at maxItems (it is default to 50):
![image](https://user-images.githubusercontent.com/39551460/112275055-78c76200-8c7f-11eb-9fc1-65e9acba50ac.png)
