### ISSUE TITLE
stealth mode failing

### ISSUE THREAD

**Issue by windowsales** [bernardro/actor-youtube-scraper#33]
It seems all attempts to scrape are failing.

Here are the errors:

"ERROR Stealth: StealthError: Failed to apply stealth trick reason: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'report-sample' 'nonce-7PyoQsK7StgoaW6nndvU9g' 'unsafe-inline'".
2021-03-12T20:49:52.869Z ",

2021-03-12T20:50:03.949Z ERROR Request https://www.youtube.com/watch?v=BDZ6ujYN610 failed too many times

**Comment by pauljamess** [comment]
I am also having this issue

**Comment by metalwarrior665** [comment]
Hey guys, should be fixed, can you try now please?
