### ISSUE TITLE
Each request fails with timeout error

### ISSUE THREAD

**Issue by AndreyBykov** [bernardro/actor-youtube-scraper#4]
Looks like they changed something on the site. Selector is there, but each request fails with: 
`TimeoutError: waiting for XPath \"//ytd-video-primary-info-renderer/div/h1/yt-formatted-string\" failed: timeout 30000ms exceeded`

**Comment by Lucie20** [comment]
the actor works today correctly

**Comment by AndreyBykov** [comment]
Yeah, just checked and today it worked with no problem. Maybe there was some issue on the website. I will close the issue for now
