### ISSUE TITLE
Incorrect information for videos with more than 1mio views

### ISSUE THREAD

**Issue by Lucie20** [bernardro/actor-youtube-scraper#6]
Incorrect information for videos with more than 1mio views
example run - https://my.apify.com/view/runs/ZkRAZ8AY4QpcsqkBL
if a video has more than 1mio views the result shows only 1k
"Except for one of the videos where the actual views on the page are 5,369,385 but the results show only 5369"

**Comment by Lucie20** [comment]
@bernardro could you please correct the issue?

**Comment by Lucie20** [comment]
@bernardro could you please correct the issue? thank you

**Comment by bernardro** [comment]
I have pushed the code to fix this, after build issue should be fixed
