### ISSUE TITLE
update input schema

### ISSUE THREAD

**Issue by Lucie20** [bernardro/actor-youtube-scraper#7]
add the functionality to scrape as well by URL, not only search terms but as well by multiple start URLs 
for example to be able to input https://www.youtube.com/results?search_query=tristan+eckerson

**Comment by rjay98** [comment]
^ same issue here. it's requiring me to input search keywords, but I really just want to get all the videos from a certain channel

**Comment by bernardro** [comment]
This was an initial implementation of the scraper, next phase features such as the ones mentioned above will be prioritized will be added soon
